### ISSUE TITLE
 Error: Invalid name: "@xbl/raml-mocker"

### ISSUE THREAD

**Issue by yx91490** [xbl/raml-mocker#2]
安装失败,请教是什么问题?

	npm ERR! install Couldn't read dependencies
	npm ERR! Error: Invalid name: "@xbl/raml-mocker"
	npm ERR!     at ensureValidName (/usr/lib/node_modules/normalize-package-data/lib/fixer.js:281:15)
	npm ERR!     at Object.module.exports.fixNameField (/usr/lib/node_modules/normalize-package-data/lib/fixer.js:196:5)
	npm ERR!     at /usr/lib/node_modules/normalize-package-data/lib/normalize.js:29:38
	npm ERR!     at Array.forEach (native)
	npm ERR!     at normalize (/usr/lib/node_modules/normalize-package-data/lib/normalize.js:28:15)
	npm ERR!     at final (/usr/lib/node_modules/read-package-json/read-json.js:310:33)
	npm ERR!     at then (/usr/lib/node_modules/read-package-json/read-json.js:124:33)
	npm ERR!     at /usr/lib/node_modules/read-package-json/read-json.js:299:40
	npm ERR!     at fs.js:266:14
	npm ERR!     at /usr/lib/node_modules/graceful-fs/graceful-fs.js:103:5
	npm ERR! If you need help, you may report this log at:
	npm ERR!     <http://github.com/isaacs/npm/issues>
	npm ERR! or email it to:
	npm ERR!     <npm-@googlegroups.com>

	npm ERR! System Linux 2.6.32-504.el6.x86_64
	npm ERR! command "node" "/usr/bin/npm" "install"
	npm ERR! cwd /tmp/raml-mocker
	npm ERR! node -v v0.10.28
	npm ERR! npm -v 1.3.6

**Comment by xbl** [comment]
抱歉，回复的太晚。

从你的报错来看，你的node 版本和 npm 版本过低...需要升级喽
我先 close 啦，如果还有问题再 open

**Comment by yx91490** [comment]
更新完了运行npm start报错了,不太懂nodejs,什么原因?
0 info it worked if it ends with ok
1 verbose cli [ '/opt/web/nodejs/bin/node',
1 verbose cli   '/opt/web/nodejs/bin/npm',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@6.4.1
3 info using node@v10.13.0
4 verbose stack Error: missing script: start
4 verbose stack     at run (/opt/web/nodejs/lib/node_modules/npm/lib/run-script.js:155:19)
4 verbose stack     at /opt/web/nodejs/lib/node_modules/npm/lib/run-script.js:63:5
4 verbose stack     at /opt/web/nodejs/lib/node_modules/npm/node_modules/read-package-json/read-json.js:115:5
4 verbose stack     at /opt/web/nodejs/lib/node_modules/npm/node_modules/read-package-json/read-json.js:418:5
4 verbose stack     at handleExists (/opt/web/nodejs/lib/node_modules/npm/node_modules/read-package-json/read-json.js:382:20)
4 verbose stack     at fs.stat (/opt/web/nodejs/lib/node_modules/npm/node_modules/read-package-json/read-json.js:390:33)
4 verbose stack     at /opt/web/nodejs/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:287:18
4 verbose stack     at FSReqWrap.oncomplete (fs.js:155:5)
5 verbose cwd /opt/web/raml-mocker
6 verbose Linux 2.6.32-504.el6.x86_64
7 verbose argv "/opt/web/nodejs/bin/node" "/opt/web/nodejs/bin/npm" "run" "start"
8 verbose node v10.13.0
9 verbose npm  v6.4.1
10 error missing script: start
11 verbose exit [ 1, true ]

**Comment by xbl** [comment]
看起来好像执行目录不对，要在 clone 下来的目录里执行 `npm start`
