### ISSUE TITLE
能否做一个开箱即用打包好的发布版？

### ISSUE THREAD

**Issue by yx91490** [xbl/raml-mocker#6]
您好，提个建议，node本身打包也要下载一大堆东西，尤其像我这样对node这套环境不是很熟悉的人，仅仅想尝试一下却不得不望而却步。我觉得有必要做一个开箱即用的打包好的发布版本，可以让更多的人去尝试这个项目，非常感谢！

**Comment by xbl** [comment]
非常感谢您的建议，经过我的深思熟虑以及和身边朋友的讨论，开箱即用的发布版有些困难。
* 这个包会非常的大
* 有些第三方**可能**会依赖于操作系统，导致不能正常工作。
除非不使用 `Nodejs` 而采用 `Go` ,重写的成本太高了 ，没办法~

考虑到有这样需求的同学大多应该是后端开发，
我会尝试使用 docker 来屏蔽掉 `Nodejs` 安装和下载第三方包的困扰。


谢谢您的反馈~

**Comment by xbl** [comment]
https://github.com/xbl/raml-mocker/wiki/%E4%BD%BF%E7%94%A8Docker%E5%90%AF%E5%8A%A8

在最新的项目中增加了docker-compose 文件，可以让我们不再安装node环境，直接在docker 环境中运行。

Good luck！

**Comment by wind13** [comment]
没找到 docker-compose.yml 文件啊？
