### ISSUE TITLE
试用了一下发现两个问题

### ISSUE THREAD

**Issue by wind13** [xbl/raml-mocker#8]
1. 没有 docker-compose.yml 文件；
1. 没有 start 这个script，执行 `npm start` 报错；

**Comment by xbl** [comment]
谢谢您的反馈，请问您 clone 的是 https://github.com/xbl/raml-mocker-starter.git 这个地址？
启动
Mock 
Server 需要 clone 上面的链接，可以查看 Readme 文档，
本项目 npm 包，不能单独启动的...
